---
image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    description: "For serving dev"
    onOpen: ignore # User should not open the preview too soon. See https://github.com/gitpod-io/gitpod/issues/531
    visibility: public
    name: "dev"
  - port: 3001
    description: "For serving dist"
    onOpen: ignore
    visibility: public
    name: "dist"

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: nvm install --lts && npm install
    init: ui5 use openui5@latest && npm run build-self-contained && ui5 use openui5@latest --config ui5-dist.yaml
    command: npm start
vscode:
  extensions:
    - redhat.vscode-xml
    - https://github.com/SAP/xml-tools/releases/download/xml-toolkit%401.1.1/xml-toolkit-1.1.1.vsix
    - https://github.com/SAP/ui5-language-assistant/releases/download/v4.0.65/vscode-ui5-language-assistant-4.0.65.vsix
...