---
image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    description: "For serving dev"
    onOpen: notify # User should not open the preview too soon. See https://github.com/gitpod-io/gitpod/issues/531
  - port: 3001
    description: "For serving dist"
    onOpen: notify

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: nvm install --lts && npm install --global @ui5/cli && npm install --save-dev @ui5/cli
    command: npm install && ui5 use openui5@latest && npm run build-self-contained && ui5 use openui5@latest --config ui5-dist.yaml && npm run start-dist
vscode:
  extensions:
    - redhat.vscode-xml
    - https://github.com/SAP/xml-tools/releases/download/xml-toolkit%401.1.1/xml-toolkit-1.1.1.vsix
    - https://github.com/SAP/ui5-language-assistant/releases/download/v4.0.3/vscode-ui5-language-assistant-4.0.3.vsix
...