name: Bug Report
description: Report a bug in OpenUI5
type: Bug
body:
  - type: markdown
    attributes:
      value: | 
        Please have a look at our [contributing guidelines](https://github.com/SAP/openui5/blob/main/CONTRIBUTING.md#report-bugs) on reporting issues. For issues concerning SAPUI5 and not reproducible with OpenUI5 alone, please contact SAP customer support instead.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: How can we reproduce the issue?
      description: Describe the issue and provide a minimal reproducible example via a URL, either through an online code editor or one of the [Demo Kit samples](https://sdk.openui5.org/nightly/#/controls) including any necessary code edits. Alternatively, consider forking our [sample app](https://github.com/SAP/openui5-sample-app) to reproduce it.
      value: |
        1. Open https:// ...
        2. Click on ...
        
           **Issue:** ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log Output / Stack Trace
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for you to use backticks.
      render: shell
  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behavior?
      description: Tell us what you expect to happen instead.
  - type: input
    id: version-OpenUI5
    attributes:
      label: OpenUI5 version
      description: Your target OpenUI5 version(s). List of maintained OpenUI5 versions can be found at https://sdk.openui5.org/versionoverview.html.
    validations:
      required: true
  - type: textarea
    id: issue-env
    attributes:
      label: Is the issue reproducible only with specific devices, OS, or browsers?
      description: Share the environment where the issue could be observed but not in other.
      placeholder: |
        - Device name: ...
        - Touch enabled: Yes|No
        - Chromium browsers: OK|FAIL
        - Firefox: OK|FAIL
        - Safari: OK|FAIL
  - type: checkboxes
    id: checked-other-issues
    attributes:
      label: Checked other issues
      description: Please search to see if an issue already exists for the unexpected behavior you encountered.
      options:
      - label: I have searched the existing issues in this OpenUI5 repository, tried other OpenUI5 versions, devices, and systems.
        required: true
  - type: textarea
    id: issue-discussed-somewhere
    attributes:
      label: Has this issue been raised or discussed in any other places?
      placeholder: |
        - https:// ...
        - https:// ...
