---
name: Bug Report
description: Report a bug in OpenUI5
body:
  - type: markdown
    attributes:
      value: | 
        Please have a look at our [contributing guidelines](https://github.com/SAP/openui5/blob/main/CONTRIBUTING.md#report-bugs) on reporting issues.
        For issues concerning SAPUI5 and not reproducible with OpenUI5 alone, please contact SAP customer support instead.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: What is the issue and how can we reproduce it?
      description: |
        To help us understand and resolve the issue quickly, please provide a **minimal reproducible example** (required) that clearly illustrates the unexpected behavior. You can easily create one using:
        - An online JavaScript code sharing platform.
        - One of our [Demo Kit samples](https://sdk.openui5.org/nightly/#/controls), with any necessary code modifications.
        - A fork of our [OpenUI5 sample app](https://github.com/SAP/openui5-sample-app).
      value: |
        1. Open the sample https:// ...
        2. Click on ...
           **Issue:** ...
        
        '#### Log Output / Stack Trace:'
        ```shell
        ...
        ```
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What is the expected behavior?
      description: Tell us what you expect to happen instead.
  - type: input
    id: version-OpenUI5
    attributes:
      label: OpenUI5 version
      description: Share your target OpenUI5 version(s). List of maintained OpenUI5 versions can be found at https://sdk.openui5.org/versionoverview.html.
    validations:
      required: true
  - type: textarea
    id: issue-env
    attributes:
      label: Is the issue reproducible only with specific devices, OS, or browsers?
      description: Specify the environment in which the issue could be observed, but not in others.
      placeholder: |
        - Device(s): ...
        - Touch enabled: YES|NO
        - Chromium browsers: OK|FAIL
        - Firefox: OK|FAIL
        - Safari: OK|FAIL
  - type: textarea
    id: issue-discussed-somewhere
    attributes:
      label: Has this issue been previously reported or discussed elsewhere?
      placeholder: |
        - https:// ...
        - https:// ...
  - type: checkboxes
    id: issue-checked
    attributes:
      label: Issues Checked
      description: Please check if a similar issue has been reported and if your project aligns with documented best practices.
      options:
        - label: I have searched the existing issues in this OpenUI5 repository, and reviewed the relevant documentation as well as the API reference from https://sdk.openui5.org/nightly.
          required: true
...
