name: Bug Report
description: Report a bug in OpenUI5
body:
  - type: markdown
    attributes:
      value: | 
        Please have a look at our [contributing guidelines](https://github.com/SAP/openui5/blob/main/CONTRIBUTING.md#report-bugs) on reporting issues.
        > [!IMPORTANT]
        > For issues concerning **SAPUI5** and not reproducible with OpenUI5 alone, please **contact SAP customer support instead.**
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: What is the issue and how can we reproduce it?
      description: |
        To help us understand and resolve the issue efficiently, please provide a **minimal reproducible example** (required) that clearly illustrates the unexpected behavior. You can easily create one using:
        - An online JavaScript code sharing platform like [JSBin](https://jsbin.com/neyagus/edit?html,js,output), [Plunker](https://embed.plnkr.co/16J1TFICxbqETCzaxuZ0?preview=README), etc.
        - One of our [Demo Kit samples](https://sdk.openui5.org/nightly/#/controls) with any necessary code modifications.
        - A fork of our [OpenUI5 sample app](https://github.com/SAP/openui5-sample-app).
      value: |
        1. Open the sample https:// ...
        2. Click on ...
        3. ... → **Issue:** ...
        
        #### Error
        > ...
        
        #### Expected behavior
        ...
    validations:
      required: true
  - type: input
    id: version-OpenUI5
    attributes:
      label: OpenUI5 version
      description: Share your target OpenUI5 version(s). List of maintained OpenUI5 versions can be found at https://sdk.openui5.org/versionoverview.html.
    validations:
      required: true
  - type: textarea
    id: issue-env
    attributes:
      label: Is the issue reproducible only with specific devices, OS, or browsers?
      description: Specify the environment in which the issue could be observed, but not in others.
      placeholder: |
        - Device(s): ...
        - Touch enabled: YES|NO
        - Chromium browsers: OK|FAIL
        - Firefox: OK|FAIL
        - Safari: OK|FAIL
  - type: checkboxes
    id: issue-checked
    attributes:
      label: Issues Checked
      description: |
        To avoid duplicates and ensure efficient issue resolution, please double-check:
        - If a similar issue has been reported or discussed already either in this OpenUI5 repository or in community sites like [Stack Overflow](https://stackoverflow.com/search?tab=active&q=%5bsapui5%5d%20is%3aquestion&searchOn=3).
        - If your project aligns with documented best practices and [compatibility guidelines](https://sdk.openui5.org/nightly/#/topic/9638e4fce1bd45f4bebf7c219672908c).
      options:
        - label: I have searched the existing issues and reviewed the relevant documentation as well as the API reference from https://sdk.openui5.org/nightly.
          required: true
